### ISSUE TITLE
Export All only grabs the <=20 playlists currently displayed

### ISSUE THREAD

**Issue by pavelkomarov** [pavelkomarov/exportify#9]
I was confused about why the Export All functionality in watsonbox's version was taking a string when an array of playlist objects is already available. The reason is because that list is only those currently displayed, but the expected behavior is to download *all*, which has to involve querying Spotify to get the full list, 50 at a time.

Either make the button actually export all, or somehow make it clear it's intended only to grab the 20 shown so users aren't confused.

**Comment by pavelkomarov** [comment]
I've renamed it Export Group. Hopefully that's clearer. This is good enough for me and for anyone who doesn't have 400+ playlists. If people really want full capability to export all with one click (and a lot of waiting) and clamor for me to reopen this, I will consider implementing it. Until such a time as that, sayonara to this one.

**Comment by shape55** [comment]
I, for one, would love to have full capability to export all w/ 1 click, and I know many others would as well considering the countless posts I've seen over the years between the Spotify Community forum & Github from users asking how to backup all playlists.

Considering Spotify is the only desktop app I've ever used that doesn't offer the ability to backup your data, we wouldn't have to be wasting time on this if they simply included it just like every other software company does.  I, and many others, for years have requested this feature several times directly to Spotify support and on their forum but they don't acknowledge it.

There are a good % of users who have hundreds of playlists, or even 1000+, but the reasoning shouldn't matter when it comes to backing up your data.  Since you asked though, there are many reasons why someone would have a large quantity.  Many are in the music business, such as myself, and for others it's a passionate hobby.  One thing to consider is that there isn't a bookmark/favorites feature for playlists & albums, so the only way to access them quickly again is to follow/save them, which then adds them to your playlists (saving albums into their own category was a more recently added feature).  Many of these I haven't even listened to before, and others I may quickly scan thru once to see if I can find a single track that suits what I'm looking for.  But most of my playlists are organized by subgenre within genre folders, and a lot of them serve as a way to keep track of albums I'd like to eventually listen to if time allows.

Just like I have 500+ films in my watchlist and 100+ books in my reading list, most of which I'll probably never have time to see/read, at least I'm able to organize, reference, and backup such lists to attempt to keep track of the near infinite amount of inspiring creations in the world.

**Comment by pavelkomarov** [comment]
It's a fair point. The other forks of this repo don't really work because of rate limit issues. Since I've solved those, I may as well integrate the less-difficult solution to the grab-all-playlists problem so users actually have this capability no one has yet been able to deliver.

**Comment by pavelkomarov** [comment]
All right. I just implemented it. It works for me, but I have many fewer playlists than you, so, @shape55, let me know what happens under greater stress.

**Comment by pavelkomarov** [comment]
Okay, I'm going to go ahead and assume this works since y'all haven't complained.

**Comment by shape55** [comment]
Sorry for the delayed response.  Many thanks for working on this.  Yes, I've tried a few of the other forks and they all had the same problem w/ the Export All button.

I just tested it out 3 times and it exported 413 out of a total of 477 playlists in each zip file, but I saw errors displayed at the top for only the same 2 glitchy, failed playlists I reported before.  It took about a half hour to complete.  Let me know if/how I should send you a log, or if there's another way to see if other playlists had the same type of failure.

**Comment by pavelkomarov** [comment]
Strange. Can you get the 61 missing playlists that you think should work one by one from my app? I'm fetching playlists 50 at a time from the list of playlists associated with the user. 61 > 50, and I was pretty careful with my loop, so I don't think this is an off-by-one error where I just missed the last batch. The missing ones wouldn't happen to all be at the end, would they?

If a playlist fails the try/catch, then it should be displayed at the top of the page until the next one comes along and replaces it (which could be in the blink of an eye if they're next to each other). But I'm not keeping a log of the failures anywhere.

**Comment by shape55** [comment]
Well, the 3 that I know for sure could not export produced the same [undefined error](https://github.com/pavelkomarov/exportify/issues/10#issuecomment-513090962) from issue #10, and they were scattered across the pages, the Local Files Playlist being on pg 1.  If I try to export these alone they return the same error.

Glad you added this ability to the Console, b/c otherwise I wouldn't know which ones are missing without going thru thru the entire folder list and comparing 1 by 1.  I ran the Export All again w/ the Console open, and I saw 1 more playlist show up there w/ the undefined error, but when the process completed the Console was cleared.  Is there a way I can prevent this (the "Persist Logs" checkbox?), or do you have to do something on your end?

I'll add the other 2 failed playlists to #10.

**Comment by shape55** [comment]
Sometimes the app resets itself during export while I'm away from the computer, like this:

Local Files Playlist failure caught. TypeError: features[i] is undefined exportify.js:179:13
Convextion failure caught. TypeError: features[i] is undefined exportify.js:179:13
Navigated to https://pavelkomarov.com/exportify/app
Super Chilled Beats (Archive) failure caught. TypeError: NetworkError when attempting to fetch resource. exportify.js:179:13
GEThttps://pavelkomarov.com/exportify/app
[HTTP/2.0 200 OK 209ms]
GEThttps://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css
[HTTP/2.0 200 OK 203ms]
GEThttps://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
[HTTP/2.0 200 OK 132ms]
GEThttps://unpkg.com/react@16/umd/react.production.min.js
[HTTP/2.0 302 Found 289ms]
GEThttps://unpkg.com/react-dom@16/umd/react-dom.production.min.js
[HTTP/2.0 302 Found 348ms]
GEThttps://pavelkomarov.com/exportify/FileSaver.js
[HTTP/2.0 200 OK 36ms]
GEThttps://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js
[HTTP/2.0 200 OK 193ms]
GEThttps://pavelkomarov.com/exportify/style.css
[HTTP/2.0 200 OK 27ms]
GEThttps://pavelkomarov.com/exportify/exportify.js
[HTTP/2.0 200 OK 41ms]
GEThttps://unpkg.com/react-dom@16.8.6/umd/react-dom.production.min.js
[HTTP/2.0 200 OK 39ms]
GEThttps://unpkg.com/react@16.8.6/umd/react.production.min.js
[HTTP/2.0 200 OK 38ms]
GEThttps://pavelkomarov.com/exportify/favicon.png
[HTTP/2.0 200 OK 44ms]

​

**Comment by pavelkomarov** [comment]
So far as I know, there isn't a way to clear the console from inside javascript. I'm certainly not clearing it. Maybe you need to configure it to show logs older than some time, but I don't see a "persist logs" on mine. The trash can icon clears everything, but only when clicked.

**Comment by shape55** [comment]
Ok, I'm using the latest Firefox version and there is a Persist Logs checkbox to the top-right of the Console.  Anyhow, before I saw your message I ran the app again w/ this checked and I was able to see a complete log after the export finished.  I caught all the ones with errors before manually, and there's only 4 total in my playlists.  The 5th one (Super Chilled Beats (Archive): 2GZIwHEvxvCCuO1EkAkOLP), as you saw, shows Network Error, which has to be b/c it was cut off during the process when I assume the page reloaded.

And I think I figured out why there are so may missing playlists.  A lot of them have duplicate names.  This is b/c they are subgenres that reside in different folders.  With some subgenres there are 3 playlists with the exact same name.  I guess it's not set to rename the file (appending a number at the end) if the name already exists?

**Comment by pavelkomarov** [comment]
Oo, good call. Right now `zip.file(PlaylistExporter.fileName(playlist), csv);` is all I'm using to put the comma-separated-value string in the output. I just tried with a minimal example:

```
zip.file("hello.txt", "hello1");
zip.file("hello.txt", "hello2");
zip.file("world.txt", "world");
```

And the output `.zip` contains `hello.txt` and `world.txt`, content "hello2" and "world", respectively. So things with identical names are getting replaced.

I didn't even know it was possible to have playlists named the same thing in Spotify, but it makes sense. I'll open a new bug to address this.

In the mean time I've added a couple debug lines:

```
console.log('nplaylists = ', nplaylists);
console.log('length of playlists list = ', playlists.length);
```

If you run it now, it should at least show that it's finding all 470something.
